version: '3'
services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - home:/home
      - var:/var
      - etc:/etc
      - usr:/usr
volumes:
   home: {}
   var: {}
   etc: {}
   usr: {}
